### ISSUE TITLE
Want to add features to support animal pedigrees - should I fork?

### ISSUE THREAD

**Issue by bmcollier** [phenotips/open-pedigree#44]
Hi - I'd like to adapt this tool to cover animal pedigrees. I'm assuming that this would be more of a fork situation than a case of submitting pull requests, as the changes would be fairly major and would require some major feature flags if they were kept in this version.

As a matter of courtesy, I thought it'd be worthwhile checking with you to see if you agreed.

**Comment by bmcollier** [comment]
Just as an update, I've forked Open Pedigree to https://github.com/bmcollier/lineage and I'll be making some fairly major changes to support animal genetics and breeding. I'll try to make pull requests back to here for any features which seem to be relevant. If there are any concerns, please let me know. I'll make it profoundly clear where the fork comes from and whose shoulders we're standing on!

**Comment by buske** [comment]
@bmcollier Thank you very much for reaching out and sharing your activity. A fork does seem most appropriate in this case. Appreciate the acknowledgement and best of luck in the project!
