### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by lihaicheng7003** [phenotips/open-pedigree#71]
using docker deploy open-pedigree

```shell
git clone git@github.com:phenotips/open-pedigree.git
docker build . -t open-pedigree
# docker-compose.yaml
# version: '3.9'
# services:
#    open-pedigree:
#        image: open-pedigree
#        ports:
#            - '9000:9000'
docker-compose up -d
````

I'm getting an error on import data

![image-20240702142625671](https://7niu.lihaicheng.cn/picgo/20240702/14-26-26-1ee4027171417a6aef23d2b72982d1d9-image-20240702142625671-21c036.png)

**Comment by dconlan** [comment]
I tried this and didn't get the issue.

What browser are you using, and is there any additional information in the console?

**Comment by lihaicheng7003** [comment]
chrome 126.0.6478.127 (64)，

It must have been one of the Chrome extensions I installed that caused the issue. The newly installed Firefox works fine. 

Thank you, I hadn’t considered the browser factor before.
