### ISSUE TITLE
clinical  property error

### ISSUE THREAD

**Issue by lihaicheng7003** [phenotips/open-pedigree#72]
I tried to select ‘Affected’ in the clinical section and fill in the disorders, but encountered a pop-up error.

![image](https://github.com/phenotips/open-pedigree/assets/61043072/8f21ceee-8b6b-40a9-aec9-2fd9a1e43de0)

**Comment by shermanlo77** [comment]
This is a replicate of Issue #2 , you should check out PR #56 and/or the fork from [MCGM](https://github.com/Manchester-Centre-for-Genomic-Medicine/open-pedigree) for their solution

**Comment by lihaicheng7003** [comment]
Thank you again, this helped me solve problem.

**Comment by lihaicheng7003** [comment]
A very useful tool, thanks to all the developers.
